---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-reader-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-reader-role
rules:
  - verbs:
      - get
    apiGroups:
      - 'batch'
    resources:
      - jobs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-reader-sa-role-binding
subjects:
  - kind: ServiceAccount
    name: job-reader-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: job-reader-role
---
apiVersion: v1
kind: Secret
metadata:
  name: job-reader-secret
  annotations:
    kubernetes.io/service-account.name: job-reader-sa
type: kubernetes.io/service-account-token